name: Deploy to VPS

on:
  push:
    branches:
      - feat/cicd

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Install dependencies
      run: npm install

    - name: Build project
      run: npm run build

    - name: Display SSH Private Key
      run: |
        echo "$SSH_PRIVATE_KEY" > ~/.ssh/id_rsa
        cat ~/.ssh/id_rsa

    - name: Set permissions for the SSH key
      run: chmod 600 ~/.ssh/id_rsa

    - name: Deploy to VPS
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.REMOTE_HOST }}
        username: ${{ secrets.REMOTE_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        port: 22
        script: |
          rsync -rltgoDzvO --delete build/ ${{ secrets.REMOTE_USER }}@${{ secrets.REMOTE_HOST }}:${{ secrets.REMOTE_PATH }}